services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "library_api"
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql  # Volume para persistência dos dados do MySQL
