name: Continuous Integration

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.
      - name: run install, build an test
        run: |
          npm install
          npm run build
          npm run test